//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARS_AVAILABILTY_CONTROL_TAB
    {
        public string LOCATION_NO { get; set; }
        public string AVAILABILITY_CONTROL_ID { get; set; }
        public string REQUESTED_BY { get; set; }
        public Nullable<System.DateTime> ROWVERSION { get; set; }
        public string WAREHOUSE { get; set; }
    }
}
